# Generated by Django 3.2.5 on 2021-07-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20210709_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='date_added',
            field=models.DateField(),
        ),
    ]
